<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="p3at">

 <xacro:property name="wheel_radius" value="0.095"/>
 <xacro:property name="wheel_thickness" value="0.04"/>
 <xacro:property name="wheel_separation" value="0.4"/>
 <xacro:property name="wheel_joint_offset_y" value="0.2"/>
 <xacro:property name="wheel_joint_offset_x" value="0.2"/>

 <xacro:macro name="wheel" params="prefix parent_link x_loc y_loc">
 <link name="${prefix}_wheel_link">
  <visual>
   <geometry>
     <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
   </geometry>
   <material name="black">
     <color rgba="0.0 0.0 0.0 1.0"/>
   </material>
  </visual>
 <collision>
  <geometry>
    <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
  </geometry>
 </collision>
 <inertial>
   <mass value="0.1"/>
   <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
 </inertial>
 </link>
 
 <joint name="${prefix}_wheel_joint" type="continuous">
 <parent link="${parent_link}"/>
 <child link="${prefix}_wheel_link"/>
 <origin xyz="${x_loc} ${y_loc} 0" rpy="1.570795 0 0"/>
 <axis xyz="0 1 0"/>
 </joint>
 </xacro:macro>
 <link name="base_link">
 <visual>
 <geometry>
 <box size="${wheel_separation} ${wheel_separation + 0.1} 0.2"/>
 </geometry>
 <material name="blue">
 <color rgba="0.2 0.5 0.8 1.0"/>
 </material>
 </visual>
 <collision>
 <geometry>
 <box size="${wheel_separation} ${wheel_separation + 0.1} 0.2"/>
 </geometry>
 </collision>
 <inertial>
 <mass value="10"/>
 <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
 </inertial>
  </link>
  
  <xacro:wheel prefix="front_right" parent_link="base_link" x_loc="${wheel_joint_offset_x}"
y_loc="${-wheel_joint_offset_y}"/>
 <xacro:wheel prefix="front_left" parent_link="base_link" x_loc="${wheel_joint_offset_x}"
y_loc="${wheel_joint_offset_y}"/>
 <xacro:wheel prefix="rear_right" parent_link="base_link" x_loc="${-wheel_joint_offset_x}"
y_loc="${-wheel_joint_offset_y}"/>
 <xacro:wheel prefix="rear_left" parent_link="base_link" x_loc="${-wheel_joint_offset_x}"
y_loc="${wheel_joint_offset_y}"/>
 <gazebo>
 <plugin name="gazebo_ros_diff_drive" filename="libgazebo_ros_diff_drive.so">
 <ros>
 <namespace>${robot_name}</namespace>
 </ros>
 <left_joint>rear_left_wheel_joint</left_joint>
 <right_joint>rear_right_wheel_joint</right_joint>
 <wheel_separation>0.4</wheel_separation>
 <wheel_diameter>0.19</wheel_diameter>
 <topicName>cmd_vel</topicName>
 <odometryTopic>odom</odometryTopic>
 <odometryFrame>odom</odometryFrame>
 <robotBaseFrame>base_link</robotBaseFrame>
 </plugin>
 </gazebo>
</robot>

